import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "skills.db")

# ↓↓↓ Paste your huge lists here ↓↓↓
HARD_SKILLS = [
"python", "java", "c++", "sql", "javascript", "typescript", "ruby", "go", "rust", "scala",
"php", "swift", "kotlin", "r", "matlab", "perl", "haskell", "elixir", "clojure", "dart",
"c#", "object oriented programming", "functional programming", "design patterns", "solid principles",
"data structures", "algorithms", "sorting algorithms", "search algorithms", "graph theory",
"dynamic programming", "recursion", "big o notation", "time complexity", "space complexity",
"data modeling", "etl", "data warehouse", "data lake", "data pipeline", "data integration",
"data governance", "data quality", "data mining", "data visualization", "machine learning",
"supervised learning", "unsupervised learning", "reinforcement learning", "deep learning",
"neural networks", "computer vision", "natural language processing", "statistics",
"descriptive statistics", "inferential statistics", "hypothesis testing", "regression analysis",
"probability", "bayesian statistics", "stochastic processes", "cloud computing",
"distributed systems", "microservices", "serverless architecture", "api design", "rest api",
"graphql", "soap api", "json", "xml", "yaml", "protobuf", "version control",
"unit testing", "integration testing", "end to end testing", "tdd", "bdd", "ci cd",
"devops", "agile methodology", "scrum", "kanban", "web development", "frontend development",
"backend development", "full stack development", "mobile development", "ios development",
"android development", "cybersecurity", "network security", "encryption", "blockchain",
"smart contracts", "cryptography", "database design", "normalization", "acid properties",
"nosql databases", "graph databases", "time series databases", "mathematics", "linear algebra",
"calculus", "discrete mathematics", "probability theory", "statistical modeling", "data analysis",
"supervised machine learning", "unsupervised machine learning", "deep neural networks",
"convolutional neural networks", "recurrent neural networks", "natural language processing",
"computer vision", "time series analysis", "bayesian inference", "hypothesis testing",
"a b testing", "feature engineering", "model deployment", "mlops", "big data processing",
"hadoop", "spark", "kafka", "data pipelines", "etl processes", "sql querying",
"nosql databases", "data warehousing", "cloud computing platforms", "aws", "azure", "gcp",
"docker", "kubernetes", "version control systems", "git", "programming fundamentals",
"object oriented design", "functional programming paradigms", "api development", "restful services",
"graphql apis", "web scraping", "data visualization tools", "tableau", "power bi", "matplotlib",
"seaborn", "ggplot2", "experimental design", "causal inference", "reinforcement learning algorithms",
"computer aided design", "cad", "solidworks", "autocad", "finite element analysis", "fea",
"computational fluid dynamics", "cfd", "structural analysis", "thermodynamics", "heat transfer",
"fluid mechanics", "materials science", "kinematics", "dynamics", "vibration analysis",
"control systems", "mechatronics", "robotics", "additive manufacturing", "3d printing",
"cnc machining", "welding", "casting", "prototyping", "testing", "machine design",
"product development", "quality control", "lean manufacturing", "six sigma", "project management",
"electrical engineering", "civil engineering", "chemical engineering", "industrial engineering",
"aerospace engineering", "automotive engineering", "environmental engineering", "geotechnical engineering",
"structural engineering", "hydraulics", "pneumatics", "surveying", "gis", "bim",
"network configuration", "cisco routing", "switching", "firewall management", "vpn setup",
"wireshark packet analysis", "windows server management", "linux server management", "ip addressing",
"subnetting", "troubleshooting", "cybersecurity protocols", "cloud networking", "wireless networking",
"network security", "encryption techniques", "intrusion detection", "penetration testing",
"system administration", "database administration", "virtualization", "vmware", "hyper v",
"active directory", "powershell scripting", "bash scripting", "shell scripting", "devops practices",
"ci cd pipelines", "containerization", "orchestration", "monitoring tools", "prometheus",
"grafana", "elasticsearch", "kibana", "log management", "incident response", "disaster recovery",
"backup strategies", "load balancing", "high availability", "sd wan", "network automation",
"ansible", "terraform", "python scripting for networking", "api integration", "rest api development",
"soap services", "json parsing", "xml processing", "data encryption standards", "pci compliance",
"hipaa compliance", "gdpr compliance", "risk assessment", "vulnerability scanning",
"adobe photoshop", "adobe illustrator", "adobe indesign", "figma", "sketch", "ui design",
"ux design", "wireframing", "prototyping", "user research", "usability testing", "graphic design",
"typography", "color theory", "layout design", "branding", "logo design", "illustration",
"motion graphics", "video editing", "adobe premiere", "adobe after effects", "3d modeling",
"blender", "maya", "cinema 4d", "web design", "html", "css", "javascript frameworks",
"responsive design", "accessibility standards", "seo optimization", "content management systems",
"wordpress", "shopify", "digital photography", "photo editing", "vector graphics", "raster graphics",
"print design", "packaging design", "environmental design", "interaction design", "service design",
"financial modeling", "accounting", "financial analysis", "budgeting", "forecasting",
"excel advanced functions", "quickbooks", "sap", "oracle financials", "tax preparation",
"auditing", "risk management", "investment analysis", "portfolio management", "corporate finance",
"valuation techniques", "mergers and acquisitions", "financial reporting", "ifrs", "gaap",
"cost accounting", "managerial accounting", "treasury management", "cash flow analysis",
"credit analysis", "derivatives", "hedging strategies", "blockchain finance", "cryptocurrency trading",
"fintech development", "regulatory compliance", "anti money laundering", "kyc procedures",
"seo", "sem", "content marketing", "social media marketing", "email marketing", "ppc advertising",
"google ads", "facebook ads", "analytics", "google analytics", "conversion rate optimization",
"a b testing", "copywriting", "brand strategy", "market research", "consumer behavior analysis",
"influencer marketing", "affiliate marketing", "video marketing", "podcast production",
"public relations", "crisis management", "event planning", "sales funnel optimization",
"lead generation", "crm management", "hubspot", "salesforce", "marketing automation",
"growth hacking", "viral marketing", "medical terminology", "cpr", "first aid", "patient care",
"vital signs monitoring", "infection control", "hipaa compliance", "electronic health records",
"medical coding", "icd 10", "cpt coding", "phlebotomy", "ekg administration", "wound care",
"medication administration", "iv therapy", "radiology", "ultrasound", "mri operation",
"ct scanning", "surgical assistance", "sterile processing", "laboratory techniques", "histology",
"cytology", "pharmacy dispensing", "compounding", "patient education", "health informatics",
"telemedicine", "rehabilitation therapy", "occupational therapy", "physical therapy",
"speech therapy", "nursing assessment", "care planning", "cnc machining", "welding",
"casting", "forging", "assembly line operations", "quality assurance", "six sigma methodologies",
"lean manufacturing principles", "supply chain management", "inventory control", "logistics",
"erp systems", "sap erp", "oracle erp", "automation systems", "plc programming",
"robotics programming", "3d printing", "additive manufacturing", "materials testing",
"failure analysis", "root cause analysis", "process optimization", "kaizen", "5s methodology",
"iso standards", "environmental health and safety", "osha compliance", "hazard analysis",
"preventive maintenance", "tool and die making", "injection molding", "extrusion",
"metal fabrication", "sheet metal working", "precision measurement", "calipers", "micrometers",
"gd and t", "project planning", "budget management", "schedule management", "resource allocation",
"risk assessment", "quality management", "stakeholder management", "change management",
"procurement", "contract negotiation", "agile project management", "scrum mastery",
"kanban implementation", "waterfall methodology", "critical path method", "earned value management",
"issue tracking", "conflict resolution", "performance metrics", "kpi development",
"reporting and dashboards", "ms project", "primavera", "jira", "trello", "asana",
"vendor management", "team leadership", "decision making", "strategic planning",
"process improvement", "business analysis", "requirements gathering", "scope definition",
"milestone tracking", "post project evaluation", "lessons learned documentation",
"crisis management", "contingency planning", "resource leveling", "dependency management",
"portfolio management", "program management", "pmbok knowledge", "pmp certification preparation",
"prince2 methodology", "hybrid project management", "remote team management", "collaboration tools",
"virtual meeting facilitation", "time zone coordination", "cultural sensitivity",
"sustainability in projects", "green project management", "ai in project management",
"predictive analytics", "machine learning for forecasting", "blockchain for project tracking",
"iot integration", "cybersecurity in projects", "data privacy compliance", "gdpr in projects",
"devops integration", "ci cd in projects", "cloud project management", "saas implementation",
"enterprise architecture", "it governance", "cobit framework", "togaf certification",
"business continuity planning", "disaster recovery planning", "incident management",
"service level agreements", "kpi monitoring", "dashboard creation", "bi tools",
"power bi development", "tableau visualization", "qlikview", "looker", "d3 js",
"ggplot", "plotly", "seaborn visualization", "matplotlib plotting", "spark processing",
"hadoop ecosystem", "airflow orchestration", "talend etl", "informatica powercenter",
"pentaho data integration", "redshift warehousing", "bigquery querying", "s3 storage",
"ec2 instances", "lambda functions", "terraform infrastructure", "ansible configuration",
"jenkins pipelines", "circleci workflows", "github actions", "gitlab ci", "bitbucket pipelines",
"confluence documentation", "slack integration", "microsoft teams collaboration", "zoom facilitation",
"oracle database management", "mongodb nosql", "cassandra distributed", "redis caching",
"elasticsearch searching", "neo4j graph", "prometheus monitoring", "grafana dashboards",
"splunk logging", "new relic performance", "datadog analytics", "vscode editing",
"intellij development", "eclipse ide", "pycharm python", "jupyter notebooks", "r studio",
"spyder ide", "postman api testing", "insomnia rest", "swagger documentation", "nginx server",
"apache web server", "tomcat application", "rabbitmq messaging", "activemq queuing",
"redis queue", "celery task management", "windows server administration", "powershell automation",
"unix administration", "macos support", "virtualbox virtualization", "vmware esxi",
"hyper v virtualization", "helm kubernetes", "istio service mesh", "linkerd proxy",
"consul service discovery", "vault secrets management", "firebase backend", "heroku deployment",
"netlify hosting", "vercel ci cd", "salesforce crm", "hubspot marketing", "marketo automation",
"adobe analytics", "google analytics", "mixpanel events", "amplitude user behavior",
"segment data pipelines", "looker bi", "sisense analytics", "d3 js visualization",
"ggplot2 plotting", "matplotlib data viz", "seaborn statistical viz", "plotly interactive",
"spark big data", "hadoop distributed", "airflow workflows", "talend integration",
"informatica etl", "pentaho bi", "redshift data warehouse", "bigquery ml", "s3 object storage",
"ec2 cloud computing", "lambda serverless", "terraform iac", "ansible automation",
"jenkins devops", "circleci ci", "github actions workflows", "gitlab pipelines", "bitbucket repo",
"confluence wiki", "slack communication", "microsoft teams meetings", "zoom video conferencing",
"oracle db", "mongodb database", "cassandra db", "redis db", "elasticsearch engine",
"neo4j db", "prometheus metrics", "grafana visualization", "splunk siem", "new relic monitoring",
"datadog apm", "vscode code", "intellij idea", "eclipse java", "pycharm ide", "jupyter lab",
"r studio ide", "spyder python", "postman testing", "insomnia api", "swagger openapi",
"nginx proxy", "apache http", "tomcat servlet", "rabbitmq queue", "activemq broker",
"redis stream", "celery distributed", "windows server", "powershell scripts", "unix shell",
"macos admin", "virtualbox vm", "vmware workstation", "hyper v manager", "helm charts",
"istio mesh", "linkerd service", "consul discovery", "vault security", "firebase auth",
"heroku paas", "netlify static", "vercel serverless", "salesforce apex", "hubspot cms",
"marketo emails", "adobe experience", "google tag manager", "mixpanel analytics", "amplitude growth",
"segment io"
]

SOFT_SKILLS = [
"communication", "written communication", "oral communication", "verbal communication", "public speaking",
"presentation skills", "active listening", "listening skills", "constructive feedback", "feedback reception",
"teamwork", "collaboration", "cross functional collaboration", "remote collaboration", "cooperation",
"coordination", "idea exchange", "team building", "leadership", "mentoring",
"coaching", "coaching and mentoring", "delegation", "task delegation", "decision making",
"time management", "prioritization", "multitasking", "scheduling", "planning",
"goal setting", "problem solving", "creative problem solving", "problem analysis", "root cause analysis",
"critical thinking", "analytical skills", "analytical thinking", "data driven decision making", "logical reasoning",
"deductive reasoning", "observation", "critical observation", "brainstorming", "adaptability",
"flexibility", "resilience", "stress management", "attention to detail", "organizational skills",
"initiative", "proactivity", "self motivation", "self-motivation", "work ethic",
"integrity", "empathy", "emotional intelligence", "conflict resolution", "conflict management",
"negotiation", "persuasion", "persuasion and negotiation", "customer service", "quality client service",
"client management", "stakeholder management", "project management", "risk management", "strategic thinking",
"innovation", "creativity", "learning agility", "continuous learning", "active learning",
"willingness to learn", "cultural awareness", "diversity inclusion", "ethical judgment", "professionalism",
"networking", "relationship building", "interpersonal skills", "interpersonal communication", "self-management",
"optimism", "calmness", "self-control", "positive attitude", "assertiveness",
"depersonalization", "taking responsibility", "positivity", "confidence", "receptive attitude",
"curiosity", "tenacity", "honesty", "accepting criticism", "motivation",
"charisma", "patience", "enthusiasm", "sociability", "aesthetics",
"system analysis", "accuracy", "open-mindedness", "accountability", "empathy and open-mindedness",
"self-direction", "drive", "thinking skills", "learning from others", "experimentation",
"questioning", "management skills", "authenticity", "mentorship", "generosity",
"cultural intelligence", "humor", "tolerance", "diplomacy", "responsibility",
"discipline", "dependability", "commitment", "introspection", "acuity",
"results-oriented", "cultural competence", "goal-setting", "trustworthiness", "writing",
"financial management", "humility", "intercultural communication", "self-awareness", "research",
"research skills", "ability to work well under pressure", "working well under pressure", "data interpretation", "troubleshooting",
"risk assessment", "evaluation and judgement", "information synthesis", "acting independently", "anticipating problems",
"recruitment", "budgeting", "strategy development", "storytelling", "mediation",
"imagination", "mind-mapping", "analysis", "self-regulation", "social skills",
"non-verbal communication", "body language reading", "questioning skills", "feedback giving", "inspiration",
"empowerment", "consensus building", "facilitation", "arbitration", "sales skills",
"teaching", "training", "public relations", "crisis management", "change management",
"organizational development", "performance management", "talent management", "succession planning", "diversity management",
"inclusion practices", "equity awareness", "bias recognition", "global mindset", "multilingualism",
"cross-cultural communication", "virtual communication", "email etiquette", "phone etiquette", "meeting facilitation",
"idea generation", "conceptual thinking", "abstract thinking", "inductive reasoning", "systems thinking",
"holistic thinking", "detail-oriented", "big picture thinking", "visionary thinking", "entrepreneurial mindset",
"business acumen", "customer focus", "user-centric thinking", "active empathy", "compassionate leadership",
"servant leadership", "transformational leadership", "transactional leadership", "situational leadership", "authentic leadership",
"ethical leadership", "inclusive leadership", "collaborative leadership", "agile leadership", "resilience building",
"stress tolerance", "burnout prevention", "work-life balance", "self-care", "mindfulness",
"emotional resilience", "cognitive flexibility", "behavioral flexibility", "adaptability to change", "quick learning",
"fast adaptation", "lifelong learning", "knowledge sharing", "peer learning", "counseling",
"advising", "guidance", "supportiveness", "helpfulness", "generosity",
"altruism", "volunteerism", "community involvement", "social responsibility", "environmental awareness",
"sustainability mindset", "ethical decision-making", "moral reasoning", "transparency", "ownership",
"self-starter", "independent working", "autonomous decision-making", "goal alignment", "performance tracking",
"self-evaluation", "peer review", "360 feedback", "constructive criticism", "growth mindset",
"divergent thinking", "convergent thinking", "lateral thinking", "out-of-the-box thinking", "disruptive innovation",
"incremental improvement", "kaizen mindset", "continuous improvement", "quality focus", "excellence pursuit",
"meticulousness", "thoroughness", "diligence", "persistence", "grit",
"determination", "ambition", "passion", "zeal", "energy",
"vitality", "presence", "executive presence", "gravitas", "poise",
"composure", "calmness under pressure", "crisis handling", "emergency response", "quick thinking",
"decisiveness", "intuition", "risk taking", "calculated risks", "venture spirit",
"adventurousness", "exploration", "discovery", "investigative skills", "puzzle solving",
"strategic planning", "tactical execution", "operational efficiency", "process optimization", "workflow management",
"bottleneck identification", "lean thinking", "agile practices", "reliability", "punctuality",
"self-confidence", "humility", "tolerance", "diplomacy", "tact",
"discretion", "loyalty", "commitment", "enthusiasm", "optimism",
"perseverance", "tenacity", "resourcefulness", "versatility", "open-mindedness",
"curiosity", "self-awareness", "social skills", "interpersonal communication", "non-verbal communication",
"body language reading", "listening skills", "questioning skills", "feedback giving", "motivation",
"inspiration", "empowerment", "team building", "consensus building", "facilitation",
"mediation", "arbitration", "sales skills", "marketing skills", "teaching",
"training", "public relations", "crisis management", "change management", "organizational development",
"performance management", "talent management", "succession planning", "diversity management", "inclusion practices",
"equity awareness", "bias recognition", "cultural competence", "global mindset", "language proficiency",
"multilingualism", "cross-cultural communication", "virtual communication", "email etiquette", "phone etiquette",
"meeting facilitation", "brainstorming", "idea generation", "conceptual thinking", "abstract thinking",
"logical reasoning", "deductive reasoning", "inductive reasoning", "systems thinking", "holistic thinking",
"detail-oriented", "big picture thinking", "visionary thinking", "entrepreneurial mindset", "business acumen",
"financial literacy", "customer focus", "user-centric design thinking", "empathy mapping", "journey mapping",
"active empathy", "compassionate leadership", "servant leadership", "transformational leadership", "transactional leadership",
"situational leadership", "authentic leadership", "ethical leadership", "inclusive leadership", "collaborative leadership",
"agile leadership", "resilience building", "stress tolerance", "burnout prevention", "work-life balance",
"self-care", "mindfulness", "emotional resilience", "cognitive flexibility", "behavioral flexibility",
"adaptability to change", "quick learning", "fast adaptation", "lifelong learning", "knowledge sharing",
"peer learning", "mentoring others", "coaching skills", "counseling", "advising",
"guidance", "supportiveness", "helpfulness", "generosity", "altruism",
"volunteerism", "community involvement", "social responsibility", "environmental awareness", "sustainability mindset",
"ethical decision-making", "moral reasoning", "integrity in action", "honesty", "transparency",
"accountability", "responsibility", "ownership", "initiative taking", "proactiveness",
"self-starter", "independent working", "autonomous decision-making", "self-management", "time blocking",
"goal setting", "objective alignment", "performance tracking", "self-evaluation", "peer review",
"360 feedback", "constructive criticism", "receptiveness to feedback", "growth mindset", "fixed mindset avoidance",
"innovation fostering", "creativity techniques", "divergent thinking", "convergent thinking", "brainstorming facilitation",
"mind mapping", "lateral thinking", "out-of-the-box thinking", "disruptive innovation", "incremental improvement",
"kaizen mindset", "continuous improvement", "quality focus", "excellence pursuit", "perfectionism",
"meticulousness", "thoroughness", "diligence", "persistence", "grit",
"determination", "ambition", "drive", "passion", "zeal",
"energy", "vitality", "charisma", "presence", "executive presence",
"gravitas", "poise", "composure", "calmness under pressure", "crisis handling",
"emergency response", "quick thinking", "decisiveness", "intuition", "gut feeling",
"risk taking", "calculated risks", "venture spirit", "adventurousness", "exploration",
"discovery", "research skills", "investigative skills", "detective mindset", "puzzle solving",
"riddle solving", "game theory application", "strategic planning", "tactical execution", "operational efficiency",
"process optimization", "workflow management", "bottleneck identification", "lean thinking", "agile practices",
"scrum participation", "kanban usage"
]

TOOLS = [
"power bi", "tableau", "excel", "ssis", "azure", "aws", "gcp", "kafka", "flink", "qlik",
"snowflake", "databricks", "azure data factory", "docker", "kubernetes", "git", "jira",
"mysql", "postgresql", "sql server", "linux", "bash", "shell scripting", "looker", "sisense",
"d3 js", "ggplot2", "matplotlib", "seaborn", "plotly", "spark", "hadoop", "airflow",
"talend", "informatica", "pentaho", "redshift", "bigquery", "s3", "ec2", "lambda",
"terraform", "ansible", "jenkins", "circleci", "github actions", "gitlab", "bitbucket",
"confluence", "slack", "microsoft teams", "zoom", "oracle database", "mongodb", "cassandra",
"redis", "elasticsearch", "neo4j", "prometheus", "grafana", "splunk", "new relic",
"datadog", "vscode", "intellij", "eclipse", "pycharm", "jupyter notebook", "r studio",
"spyder", "postman", "insomnia", "swagger", "nginx", "apache", "tomcat", "rabbitmq",
"activemq", "redis queue", "celery", "windows server", "powershell", "unix", "macos",
"virtualbox", "vmware", "hyper v", "helm", "istio", "linkerd", "consul", "vault",
"firebase", "heroku", "netlify", "vercel", "salesforce", "hubspot", "marketo",
"adobe analytics", "google analytics", "mixpanel", "amplitude", "segment", "adobe photoshop",
"adobe illustrator", "adobe indesign", "figma", "sketch", "invision studio", "xd",
"canva", "coreldraw", "gimp", "inkscape", "autodesk maya", "blender", "zbrush",
"cinema 4d", "unity", "unreal engine", "godot", "visual studio", "netbeans",
"sublime text", "atom", "notepad++", "emacs", "vim", "android studio", "xcode",
"flutter", "react native", "expo", "ionic", "cordova", "selenium", "cypress",
"appium", "junit", "testng", "pytest", "mocha", "jest", "karma", "sonarQube",
"checkmarx", "fortify", "burp suite", "metasploit", "nmap", "wireshark", "tcpdump",
"snort", "openvpn", "ansible tower", "puppet", "chef", "saltstack", "nagios",
"zabbix", "icinga", "cacti", "solarwinds", "prtg", "logicmonitor", "dynatrace",
"appdynamics", "sumo logic", "logstash", "kibana", "filebeat", "metricbeat",
"heartbeat", "packetbeat", "winlogbeat", "auditbeat", "graylog", "fluentd",
"loggly", "papertrail", "logz io", "sematext", "scalyr", "honeycomb", "lightstep",
"jaeger", "zipkin", "opentelemetry", "opentracing", "aws cloudwatch", "azure monitor",
"google cloud operations", "new relic one", "datadog apm", "instana", "signalfx",
"wavefront", "sysdig", "coralogix", "mezmo", "humio", "loki", "tempo",
"mimir", "thanos", "cortex", "victoriametrics", "influxdb", "timescaledb",
"questdb", "clickhouse", "druid", "pinot", "kudu", "impala", "presto",
"trino", "hive", "pig", "sqoop", "flume", "nifi", "streamsets",
"beam", "flink", "storm", "samza", "pulsar", "kinesis", "firehose",
"eventbridge", "sns", "sqs", "msk", "confluent platform", "zookeeper",
"etcd", "consul kv", "vault secrets", "keycloak", "okta", "auth0",
"cognito", "firebase auth", "supabase", "appwrite", "pocketbase", "strapi",
"directus", "hasura", "postgraphile", "prisma", "typeorm", "sequelize",
"knex", "bookshelf", "waterline", "mongoose", "drizzle", "kysely",
"mikro orm", "ent", "gORM", "xorm", "beego", "echo", "gin",
"fiber", "revel", "iris", "mux", "chi", "httprouter", "fasthttp",
"actix", "rocket", "warp", "tide", "poem", "axum", "tokio",
"hyper", "reqwest", "surf", "ureq", "curl rust", "serde", "jsonwebtoken",
"bcrypt", "argon2", "scrypt", "pbkdf2", "openssl", "ring", "rustls",
"sodiumoxide", "ed25519 dalek", "secp256k1", "bls12 381", "curve25519 dalek",
"web3 js", "ethers js", "viem", "hardhat", "truffle", "ganache",
"remix", "openzeppelin", "solana cli", "anchor", "serum dex", "raydium",
"orca", "metaplex", "candy machine", "arweave", "ipfs", "filecoin",
"sia", "storj", "swarm", "hypercore", "dat protocol", "libp2p",
"ipfs cluster", "orbit db", "gun db", "couchdb", "pouchdb", "leveldb",
"rocksdb", "badgerdb", "boltdb", "etcd db", "aerospike", "scylladb",
"cockroachdb", "yugabytedb", "tidb", "vitess", "planetscale", "neon",
"supabase postgres", "timescale", "citus", "greenplum", "vertica", "teradata",
"exasol", "actian", "snowflake connector", "dbt", "great expectations",
"soda sql", "monte carlo", "metaplane", "elementary data", "collibra",
"alation", "ataccama", "informatica edc", "talend data catalog", "erwin data intelligence",
"octopai", "datahub", "acryl datahub", "marquez", "amundsen", "atlas apache",
"odpi egiria", "purview", "unity catalog", "lakefs", "dremio", "starburst",
"ahana", "varada", "upsolver", "fivetran", "stitch", "matillion",
"hevo", "rudderstack", "census", "hightouch", "grouparoo", "iteratively",
"snowplow", "rudder", "segment io", "tealium", "mparticle", "appcues",
"intercom", "zendesk", "freshdesk", "helpscout", "drift", "hubspot crm",
"salesforce crm", "pipedrive", "close io", "copper", "zoho crm", "insightly",
"nimble", "capsule crm", "agile crm", "keap", "nutshell", "really simple systems",
"vtiger", "suitecrm", "odoo", "erpnext", "dolibarr", "tryton",
"openbravo", "adempiere", "idempiere", "compiere", "metasfresh", "axelor",
"apache ofbiz", "sap business one", "oracle netsuite", "microsoft dynamics 365",
"acumatica", "sage intacct", "financialforce", "workday", "xero", "quickbooks online",
"freshbooks", "wave accounting", "zoho books", "kashflow", "freeagent", "gnucash",
"manager io", "akaunting", "zipbooks", "invoiceninja", "sleek bill", "hiveage",
"blinksale", "nutcache", "ronin", "curdbee", "harvest", "toggl",
"clockify", "timely", "rescue time", "hubstaff", "time doctor", "desk time",
"actitime", "paymo", "clicktime", "tsheets", "timecamp", "everhour",
"tick", "function fox", "avaza", "mavenlink", "accelo", "scoro",
"teamwork projects", "asana", "trello", "monday com", "wrike", "clickup",
"basecamp", "smartsheet", "airtable", "notion", "coda", "quip",
"evernote", "onenote", "bear app", "obsidian", "roam research", "logseq",
"remnote", "workflowy", "dynalist", "todoist", "things", "omnifocus",
"ticktick", "any do", "wunderlist replacement", "microsoft to do", "google keep",
"apple reminders", "habitica", "forest app", "focus booster", "pomodone",
"rescuetime", "freedom app", "cold turkey", "stayfocusd", "leechblock",
"selfcontrol", "appblock", "flipd", "offtime", "moment app", "screen time",
"digital wellbeing", "qualitytime", "space app", "detox app", "siemens nx",
"catia", "solidworks", "fusion 360", "inventor", "creo parametric", "rhino 3d",
"grasshopper", "keyshot", "vray", "corona renderer", "octane render", "cycles",
"eevee", "arnold", "redshift", "maxwell render", "lumion", "enscape",
"twinmotion", "revit", "archicad", "sketchup", "vectorworks", "autocad",
"microstation", "bricscad", "zwcad", "draftSight", "librecad", "qcad",
"freecad", "openscad", "salome", "gmsh", "netgen", "ansys", "abaqus",
"comsol", "nastran", "patran", "hypermesh", "simscale", "onshape",
"solid edge", "spaceclaim", "geomagic", "meshmixer", "slicer", "cura",
"prusa slicer", "simplify3d", "chitubox", "lychee slicer", "formware",
"meshroom", "colmap", "realitycapture", "agisoft metashape", "3df zephyr",
"pix4d", "drone deploy", "webodm", "opendronemap", "micmac", "alicevision",
"openmvg", "openmvs", "pdal", "lastools", "cloudcompare", "meshlab",
"pcl", "opencv", "scikit image", "pillow", "imagemagick", "graphicsmagick",
"ffmpeg", "avconv", "handbrake", "vlc", "mpv", "potplayer",
"davinci resolve", "final cut pro", "avid media composer", "hitfilm express",
"lightworks", "openshot", "kdenlive", "shotcut", "flowblade", "olive editor",
"natron", "nuke", "fusion", "after effects", "motion", "houdini",
"mantra", "karma renderer", "substance painter", "substance designer", "mari",
"quixel mixer", "armor paint", "3d coat", "mudbox", "sculptris",
"nomad sculpt", "forger", "shapr3d", "umake", "concepts app", "procreate",
"clip studio paint", "krita", "mypaint", "firealpaca", "medibang paint",
"paint tool sai", "autodesk sketchbook", "infinite painter", "art rage", "rebelle",
"corel painter", "affinity designer", "affinity photo", "affinity publisher", "serif drawplus",
"serif photoplus", "serif pageplus", "microsoft publisher", "scribus", "lucidpress",
"canva publisher", "adobe spark", "picmonkey", "stencil", "crello", "desygner",
"visme", "venngage", "piktochart", "easelly", "infogram", "genially",
"prezi", "slides carnival", "beautiful ai", "google slides", "microsoft powerpoint",
"apple keynote", "libreoffice impress", "wps office", "onlyoffice", "zoho show",
"haiku deck", "slidebean", "emaze", "powtoon", "vyond", "animaker",
"moovly", "renderforest", "biteable", "animoto", "wideo", "explee",
"mysimpleshow", "rawshorts", "lumen5", "invideo", "wave video", "clipchamp",
"kapwing", "veed io", "headliner app", "descript", "audacity", "garageband",
"logic pro", "ableton live", "fl studio", "reaper", "cubase", "pro tools",
"studio one", "ardour", "lmms", "cakewalk", "tracktion waveform", "bitwig studio",
"reason studios", "acid pro", "sound forge", "waveform", "mixcraft",
"magix music maker", "sony acid", "adobe audition", "izotope rx", "waves plugins",
"fabfilter", "native instruments", "serum synthesizer", "massive x", "kontakt",
"battery", "reaktor", "absynth", "fm8", "guitar rig", "traktor",
"maschine", "komplete", "arturia analog lab", "pigments", "v collection",
"moog model d", "roland cloud", "korg gadget", "yamaha dx7", "novation bass station",
"behringer deepmind", "elektron digitakt", "teenage engineering op 1", "ableton push",
"akai mpc", "pioneer ddj", "numark mixtrack", "hercules dj", "virtual dj",
"serato dj", "rekordbox", "mixxx", "cross dj", "djay pro", "ultramixer",
"mixvibes", "deckadance", "zulu dj", "djuced", "djay", "spotify dj",
"soundcloud go", "beatport link", "tidal hi fi", "deezer", "amazon music hd",
"apple music", "qobuz", "roon", "audirvana", "foobar2000", "musicbee",
"aimp", "clementine", "rhythmbox", "banshee", "amarok", "strawberry",
"quod libet", "tomahawk", "gmusicbrowser", "exaile", "guayadeque", "cantata",
"deadbeef", "lollypop", "tauon music box", "elisa music player", "sayonara player",
"cmus", "moc", "ncmpcpp", "mpd", "mpc", "pianobar", "pandora client",
"spotify tui", "ncspot", "spotifyd", "mopidy", "musicpd", "ymuse",
"nuclear player", "jellyfin", "emby", "plex", "kodi", "stremio",
"popcorn time", "webtorrent", "peerflix", "butter project", "torrentv",
"ace stream", "sopcast", "tvheadend", "nextpvr", "mythtv", "sagetv",
"windows media center", "emby theater", "plex media player", "roku", "fire tv",
"apple tv", "chromecast", "nvidia shield", "xbox media player", "playstation media"
]


def populate_db():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS skills (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            category TEXT NOT NULL CHECK (category IN ('hard','soft','tools')),
            is_core INTEGER NOT NULL DEFAULT 1
        )
        """
    )

    def upsert_many(skills, category, is_core=1):
        for s in skills:
            name = s.lower().strip()
            if not name:
                continue
            cur.execute(
                """
                INSERT INTO skills (name, category, is_core)
                VALUES (?, ?, ?)
                ON CONFLICT(name) DO UPDATE
                    SET category = excluded.category,
                        is_core  = excluded.is_core
                """,
                (name, category, is_core),
            )

    # Order matters: hard first, then tools override, then soft override
    upsert_many(HARD_SKILLS, "hard", 1)
    upsert_many(TOOLS, "tools", 1)
    upsert_many(SOFT_SKILLS, "soft", 1)

    conn.commit()
    conn.close()
    print(f"Skills table populated in {DB_PATH}")


if __name__ == "__main__":
    populate_db()
